language: php
php:
  - 5.6
  - hhvm
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
sudo: false
before_script:
  - mv .env.behat.travis .env.behat
  - mv .env.blank .env
  - touch storage/acceptance/acceptance.sqlite
  - chmod -R 777 storage
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - phpunit
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml
#after_script:

