language: php
php:
  - 5.6
  - 5.5
sudo: false
before_script:
  - mv .env.behat.travis .env.behat && cp .env.behat .env
  - touch storage/acceptance/acceptance.sqlite
  - chmod -R 777 storage
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate --seed
  - cp storage/acceptance/acceptance.sqlite storage/integration/integration.sqlite
  - npm install

script:
  # Run the tests!
  - gulp test
  # Run them again!
  - phpunit
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml
