language: php
php:
  - 5.6
  - 5.5
sudo: false
before_script:
  - mv .env.behat.travis .env.behat
  - chmod -R 777 storage
  - touch storage/acceptance/acceptance.sqlite
  - composer self-update
  - composer install --prefer-source
  - composer update --prefer-source
  - php artisan flyfish
  - php artisan key:generate
script:
  - phpunit
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml
#after_script:

