language: php
php:
  - '5.6'
  - '7.0'
node_js:
  - '4.1'
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
sudo: false
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - mv .env.behat.travis .env.behat && cp .env.behat .env
  - touch storage/acceptance/acceptance.sqlite
  - chmod -R 777 storage
  - chmod -R 777 bootstrap/cache
  - composer self-update
  - composer install --prefer-source
  - php artisan key:generate
  - php artisan migrate --seed
  - cp storage/acceptance/acceptance.sqlite storage/integration/integration.sqlite
  - npm install

script:
  # Run the tests!
  - gulp test
  # Run them again!
  - phpunit
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml
