sudo: false
language: php
php:
  - 5.6

before_script:
  # setup mysql (to test production) , and sqlite (for behat acceptance)
  # update composer,
  # then grab the packages,
  # chmod storage
  # migrate and seed db

  - mv .env.travis .env

  - composer self-update
  - composer install --prefer-dist
  - chmod -R 777 storage
  - touch storage/acceptance.sqlite
  - php artisan migrate --seed
  - php artisan key:generate
  #- mysql -e 'create database travis;'

script:
    # Run them tests, y'all
  - phpunit tests/
  - vendor/bin/phpspec run -v
  - vendor/bin/behat
