sudo: false
language: php
php:
  - 5.6

before_script:
  # setup mysql (to test production) , and sqlite (for behat acceptance)
  # update composer,
  # then grab the packages,
  # chmod storage
  # migrate and seed db
  - mv .env.travis .env
  - mysql -e 'create database travis;'
  - composer self-update
  - composer install --prefer-source
  - chmod -R 777 storage
  - php artisan migrate --seed
  - php artisan key:generate
  - npm install

script:
    # Run them tests, y'all
  - gulp
