sudo: false

php:
  - 5.6

before_script:
    # update composer,
    # then grab the packages,
    # chmod storage
    # and grab chromedriver for headless browser tests

    # - composer self-update
  - php composer install --dev --prefer-dist
  - chmod -R 777 storage
  - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && unzip chromedriver_linux32_23.0.1240.0.zip && sudo mv chromedriver /usr/bin"

script:
    # Run them tests, y'all
  - phpunit tests/
  - vendor/phpspec run -v
  - vendor/bin/behat
