language: php
php:
  - 5.6
  - 5.5
matrix:
  allow_failures:
    - php: 5.5
sudo: false
before_script:
  - mv .env.behat.travis .env.behat
  - chmod -R 777 storage
  - touch storage/acceptance/acceptance.sqlite
  - composer self-update
  - composer install --prefer-source
  - composer update --prefer-source
  - php artisan flyfish
  - php artisan key:generate
  #- npm install - if you want to use gulp/elixir


script:
  # Run them tests, y'all
  #- gulp # if you are running 'npm install' in before_script
  - phpunit tests/
  - vendor/bin/phpspec run -v
  - vendor/bin/behat --config behat.yml

  after_script:
#    - php vendor/bin/coveralls -v
