sudo: false
language: php
php:
  - 5.6

before_script:
    # update composer,
    # then grab the packages,
    # chmod storage
  - composer self-update
  - composer install --prefer-dist
  - chmod -R 777 storage

script:
    # Run them tests, y'all
  - phpunit tests/
  - vendor/bin/phpspec run -v
  - vendor/bin/behat
