sudo: false
language: php
php:
  - 5.6

before_script:
    # setup mysql,
    # update composer,
    # then grab the packages,
    # chmod storage
    # migrate and seed db
  - mv .env.example .env
  - mysql -e 'create database homestead;'
  - composer self-update
  - composer install --prefer-dist
  - chmod -R 777 storage
  - php artisan migrate --seed

script:
    # Run them tests, y'all
  - phpunit tests/
  - vendor/bin/phpspec run -v
  - vendor/bin/behat
